
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5


development:
  <<: *default
  database: gcamp_development

test:
  <<: *default
  database: gcamp_test

production:
  <<: *default
  database: gcamp_production
